### ISSUE TITLE
扫描AP的时候 就会崩溃

### ISSUE THREAD

**Issue by rfvcdewsxzaq** [josark2005/esp8266_deauther_chinese#1]
这是串口接收到的数据，然后就重启了。。。
Exception (29):
epc1=0x4000df64 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

ctx: sys 
sp: 3ffffd80 end: 3fffffb0 offset: 01a0

>>>stack>>>
3fffff20:  40282420 00000000 0000000d 4020d588  
3fffff30:  402315fc 3ffef91c 3fff5c98 40231616  
3fffff40:  00000000 402313ff 3ffef934 3ffe9f30  
3fffff50:  011a6811 3ffef934 3ffe9f30 011a6811  
3fffff60:  40231890 3ffeb020 000000f5 3ffea7d8  
3fffff70:  4021bdd5 3ffeb030 00000000 3ffea7d8  
3fffff80:  4021be1a 3fffdab0 00000000 3fffdcb0  
3fffff90:  3ffe9f40 00000000 3fffa0f0 4021ba8b  
3fffffa0:  40000f49 3fffdab0 3fffdab0 40000f49  
<<<stack<<<

**Comment by josark2005** [comment]
原版没有问题吗？这个版本只是基于原作者进行了html级别的汉化，没有作任何其他改动。这个版本我亲自测试过没有问题才放上来的，可能是个别问题吧，原作者在下个版本会推出多语言支持，我也会持续跟进该项目，感谢支持。

**Comment by lzx3355669** [comment]
我也有这种问题，扫描崩溃，

**Comment by josark2005** [comment]
这个项目是基于旧版本翻译的，崩溃情况在页面中有提示，不要动等重启，重新连接后应该能正常使用。推荐使用原作者的最新版本。

**Comment by lzx3355669** [comment]
我刚刚就是用的原作者的最新版，在我的手机上一直崩溃出现错误，每次我扫描的时候都会出现
error loading apscan.json

**Comment by josark2005** [comment]
你是什么设备？

**Comment by lzx3355669** [comment]
华为p9

**Comment by lzx3355669** [comment]
刚刚我成功攻击了一个，但是之后一直提示error

**Comment by josark2005** [comment]
具体攻击教程可以看信息页

**Comment by lzx3355669** [comment]
现在可以运行，为什么刚刚不能一直提示错误，我一直刷新页面才能攻击

**Comment by josark2005** [comment]
扫描设备、开始攻击后设备可能掉线，需要重新连接后才能使用。

**Comment by josark2005** [comment]
我没有做任何功能上的改动，仅仅是翻译工作，具体的错误细节我也不是很明白，抱歉。

**Comment by lzx3355669** [comment]
没事，谢谢你的耐心回答
